id: P000050
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅༔ ༔རྡོར་སེམས་ཐུགས་ཀྱི་སྒྲུབ་པ་ལས༔ ཟབ་གཏེར་ཁ་བྱང་བཞུགས་སོ༔ ༔
  authors:
  - མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེའམ་གཏེར་བདག་གླིང་པ་དང་ལོ་ཆེན་དྷརྨ་ཤྲཱིའམ་ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།
  layers:
  - book_title
  - author
  - quotation
  - yigchung
  id: SHE-RTD-10
web_metadata:
  title:
    en: The Heart Accomplishment of Vajrasattva According to the Tradition of Mindroling
    bo: དཔལ་རྡོ་རྗེ་སེམས་དཔའ་ཐུགས་ཀྱི་སྒྲུབ་པའི་ཆོས་སྐོར་བཞུགས་སོ། ༼སྨིན་གླིང་རྡོར་སེམས།༽
  collection:
    en: Treasury of Precious Termas–  Book 10
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༡༠
  author:
    en: Authors:Lochen Dharmashri,Minling Terchen Gyurme Dorje,Ngawang Chopal Gyatso
    bo: ངག་དབང་ཆོས་དཔལ་རྒྱ་མཚོ།,དྷརྨ་ཤྲཱི།,སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-10
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-10.epub
  description:
    en: ''
    bo: ''
